import './globals.css';
import { Archivo } from 'next/font/google';

import Footer from './components/Footer';

export const dynamic = 'force-dynamic';

const archivo = Archivo({ subsets: ['latin'] });

export const metadata = {
  title: 'Walky Doggy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
